from z3 import *

s = Solver()

zero = Int('zero')
s.add(zero >= 33)
s.add(zero <= 122)
one = Int('one')
s.add(one >= 33)
s.add(one <= 122)
two = Int('two')
s.add(two >= 33)
s.add(two <= 122)
three = Int('three')
s.add(three >= 33)
s.add(three <= 122)
four = Int('four')
s.add(four >= 33)
s.add(four <= 122)
five = Int('five')
s.add(five >= 33)
s.add(five <= 122)
six = Int('six')
s.add(six >= 33)
s.add(six <= 122)
seven = Int('seven')
s.add(seven >= 33)
s.add(seven <= 122)
eight = Int('eight')
s.add(eight >= 33)
s.add(eight <= 122)
nine = Int('nine')
s.add(nine >= 33)
s.add(nine <= 122)
ten = Int('ten')
s.add(ten >= 33)
s.add(ten <= 122)
eleven = Int('eleven')
s.add(eleven >= 33)
s.add(eleven <= 122)
twelve = Int('twelve')
s.add(twelve >= 33)
s.add(twelve <= 122)
thirteen = Int('thirteen')
s.add(thirteen >= 33)
s.add(thirteen <= 122)
fourteen = Int('fourteen')
s.add(fourteen >= 33)
s.add(fourteen <= 122)
fifteen = Int('fifteen')
s.add(fifteen >= 33)
s.add(fifteen <= 122)
sixteen = Int('sixteen')
s.add(sixteen >= 33)
s.add(sixteen <= 122)
seventeen = Int('seventeen')
s.add(seventeen >= 33)
s.add(seventeen <= 122)

s.add(zero == 107)
s.add(one == 51)
s.add(two == 51)
s.add(three == 112)

s.add(four == fifteen)
s.add(five == eight)
s.add(six == twelve)

s.add((seven - four) == 42)
s.add((seven + 1) == nine)
s.add((nine % eight) == 46)
s.add((eleven - eight + two) == 99)
s.add((fourteen - six) == (seventeen + 2))
s.add(((nine % five) * 2) == (thirteen + 40))
s.add((four % thirteen) == 15)
s.add((fourteen % thirteen) == (twelve - 32))
s.add(((seven % six) + 89) == ten)
s.add((sixteen % fifteen) == 17)

s.check()
print(s.model())
